[package]
name = "mpd-pulse"
version = "0.3.0"
authors = ["matt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-pulsectl-fork = "0.2.12"
config = "0.11.0"
dirs = "4.0"
